# Generated by Django 5.2 on 2025-04-12 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parceiros', '0002_categoria_grupo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=30, null=True, verbose_name='NOME FANTASIA')),
                ('razao_social', models.CharField(blank=True, max_length=100, null=True, verbose_name='RAZÃO SOCIAL')),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ')),
                ('insc_est', models.CharField(blank=True, max_length=20, null=True, verbose_name='INSC EST')),
                ('sigla_imp', models.CharField(blank=True, max_length=5, null=True, verbose_name='SIGLA IMP')),
                ('sigla_exp', models.CharField(blank=True, max_length=5, null=True, verbose_name='SIGLA EXP')),
                ('serv_sigla_imp', models.CharField(blank=True, max_length=5, null=True, verbose_name='SIGLA IMP SERV')),
                ('serv_sigla_exp', models.CharField(blank=True, max_length=5, null=True, verbose_name='SIGLA EXP SERV')),
                ('cod_interno', models.CharField(blank=True, max_length=20, null=True, verbose_name='COD INTERNO')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='OBSERVACOES')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorias', to='parceiros.categoria')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos', to='parceiros.grupo')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parceiros.ativo')),
            ],
        ),
    ]
